import 'styles/globals.css'
import 'oldpages/AdageIframe/index.scss'
import 'oldpages/AdageIframe/app/AppLayout.scss'
import 'oldpages/AdageIframe/app/components/LoaderPage/LoaderPage.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/NoResultsPage.scss'
import 'oldpages/AdageIframe/app/components/Layout/Notification/Notification.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFiltersTags/OfferFiltersTags.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferDetails.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferSection/OfferSection.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/OfferSummary.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.scss'
import 'oldpages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/SearchBox/SearchBox.scss'
import 'oldpages/AdageIframe/app/components/Layout/Spinner/Spinner.scss'
import 'oldpages/AdageIframe/app/components/UnauthenticatedError/UnauthenticatedError.scss'
import 'oldpages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/Control/Control.scss'
import 'oldpages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/CustomOption/Option.scss'
import 'oldpages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/DropdownIndicator/DropdownIndicator.scss'
import 'oldpages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/MultiSelectAutocomplete.scss'
import 'oldpages/AdageIframe/app/ui-kit/Pellet/Pellet.scss'
import 'oldpages/Bookings/NoBookingsForPreFiltersMessage/NoBookingsForPreFiltersMessage.scss'
import 'oldpages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AddVenueProviderButton/AddVenueProviderButton.scss'
import 'oldpages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.scss'
import 'oldpages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.scss'
import 'oldpages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderFormDialog/CinemaProviderFormDialog.scss'
import 'oldpages/Reimbursements/Reimbursement.scss'
import 'oldpages/Signup/SignupContainer/MaybeAppUserDialog/MaybeAppUserDialog.scss'
import 'oldpages/Signup/SignupContainer/OperationProcedures/OperationProcedures.scss'

import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
